### ISSUE TITLE
Doesn't work with Hashtbl.t despite `bin_shape_hashtbl` being defined

### ISSUE THREAD

**Issue by rosalogia** [janestreet/ppx_bin_prot#11]
Suppose I have a type

```ocaml
type t =
    | A of (string, string) Hashtbl.t
[@@deriving bin_io]
```

I receive an error `Unbound value Hashtbl.bin_shape_t`. Clearly, `bin_shape_hashtbl` exists in `Bin_prot.Shape`, but it seems like the ppx doesn't know where to find it and instead is confused since it thinks the shape for `Hashtbl.t` must be `Hashtbl.bin_shape_t`. This seems like a bug to me, but if there's a work-around that users are intended to use, I'm not sure what that might be.

**Comment by aalekseyev** [comment]
It was a surprise to me that this definition actually exists. Maybe we should delete it, since it's not used, at least we don't use it in Jane Street (didn't check opam).

The way we serialize hastables in jane street is by using `Bin_prot.Utils.Make_iterable_binable1`, via `Core.Hashtbl.Make_binable*` or `Core.Hashtbl.Make(...)` followed by calling `Provide_bin_io` on that.

For example:

```
module String_hashtbl = Core.Hashtbl.Make_binable(String)

type t = string String_hashtbl.t [@@deriving bin_io]
```

You could do something similar, or you could try using the definitions you're referring to by doing something like this:

```
type ('a, 'b) hashtbl = ('a, 'b) Hashtbl.t

open Bin_prot.Std

type t =
    | A of (string, string) hashtbl
[@@deriving bin_io]
```

I wouldn't recommend that though, since these functions seem to be "on their way out", so my recommendation is use core or `Bin_prot.Utils.Make_iterable_binable1` directly.

Anyway, if there's a bug here, it's either that these functions exist at all, or that they have names that don't match the name of the type (the names correspond to `('a, 'b) hashtbl`, not `('a, 'b) Hashtbl.t`).  I tend to say the former.

**Comment by aalekseyev** [comment]
Sorry, actually these probably shouldn't be removed because `Base.Hashtbl.t` is not the same type as `Caml.Hashtbl.t`, it's better to improve their usability somehow, but I don't know what's a good way to do that.

**Comment by aalekseyev** [comment]
To be clear, the difficulty with improving the names of these definitions is that they need to be called `Hashtbl.bin_write_t` etc., and you can't define those without defining the module `Hashtbl`, and I don't think we want to define the module `Hashtbl` in `Bin_prot` because of all the various shadowing issues that might create.
